config/routes.rb
Rails.application.routes.draw do
  resources :remote_labs

  # Internal Slave Routes
  post 'slave/switch/toggle' => 'slaves#switch_toggle'

  # External API Routes
  post 'api/register_slave' => 'api#register_slave'
  get 'api/get_commands/:id' => 'api#get_commands'
  post 'api/complete_command' => 'api#complete_command'
  post 'api/log_data_value' => 'api#post_data_value'
  get 'api/data_values' => 'api#get_data_values'

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/command.rb
class Command < ActiveRecord::Base
  belongs_to :slave
end

app/models/data_value.rb
class DataValue < ActiveRecord::Base
  belongs_to :slave
end

app/models/remote_lab.rb
class RemoteLab < ActiveRecord::Base
  belongs_to :user
  has_many :slaves
end

app/models/slave.rb
class Slave < ActiveRecord::Base
  belongs_to :remote_lab
  has_many :commands
  has_many :data_values
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :remote_labs
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def register_slave
    id = params[:id]
    address = params[:address]
    type = params[:type]
    state = params[:state]

    remote_lab = RemoteLab.find(id)
    slave = remote_lab.slaves.find_or_create_by(address: address)
    slave.update(s_type: type, state: state)

    render json: slave.as_json
  end

  def get_commands
    commands = Command.where(:completed => false).joins(:slave).where(:slaves => {:remote_lab_id => params[:id]})
    ret_commands = []
    commands.each do |c|
      ret_command = {address: c.slave.address, input: c.input, type: c.slave.s_type, id: c.id}
      ret_commands.append(ret_command)
    end

    render json: ret_commands.as_json
  end

  def complete_command
    command = Command.find(params[:id])
    command.update(completed: true)
    render json: command.as_json
  end

  def post_data_value
    id = params[:id]
    address = params[:address]
    value = params[:value]

    remote_lab = RemoteLab.find(id)
    slave = remote_lab.slaves.find_by_address(address)
    dv = slave.data_values.create(value: value)

    render json: dv.as_json
  end

  def get_data_values
    id = params[:id]
    slave = Slave.find(id)
    if slave
      render json: slave.data_values.as_json
    else
      render status: 404
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/remote_labs_controller.rb
class RemoteLabsController < ApplicationController
  before_action :set_remote_lab, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @remote_labs = RemoteLab.all
    respond_with(@remote_labs)
  end

  def show
    respond_with(@remote_lab)
  end

  def new
    @remote_lab = RemoteLab.new
    respond_with(@remote_lab)
  end

  def edit
  end

  def create
    @remote_lab = RemoteLab.new(remote_lab_params)
    flash[:notice] = 'RemoteLab was successfully created.' if @remote_lab.save
    respond_with(@remote_lab)
  end

  def update
    flash[:notice] = 'RemoteLab was successfully updated.' if @remote_lab.update(remote_lab_params)
    respond_with(@remote_lab)
  end

  def destroy
    @remote_lab.destroy
    respond_with(@remote_lab)
  end

  private
    def set_remote_lab
      @remote_lab = RemoteLab.find(params[:id])
    end

    def remote_lab_params
      params.require(:remote_lab).permit(:title, :version, :author, :school, :user_id, :lab_type, :password, :allowable_time)
    end
end

app/controllers/slaves_controller.rb
class SlavesController < ApplicationController
  def switch_toggle
    switch_slave = Slave.find(params[:id])
    command = switch_slave.commands.create(:input => 1)
    render json: command.as_json
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/remote_labs_helper.rb
module RemoteLabsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<div class="col-md-10 col-md-offset-1">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse ">
  <div class="col-md-8 col-md-offset-2">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
<% end %>

app/views/layouts/_navigation_links_right.html.erb
<% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <%= current_user.email %> <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to 'Update Profile', edit_user_registration_path %></li>
      <% if current_user.admin? %>
        <li class="divider"></li>
        <li><%= link_to 'User Management', users_path %></li>
      <% end %>
      <li class="divider"></li>
      <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
    </ul>
  </li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Test App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Test App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <% content_for :title do %>About<% end %>
      <h3>About the Website</h3>
      <p>
        Cold-pressed fanny pack sriracha gluten-free trust fund. Cardigan Cosby sweater iPhone fanny pack. Dreamcatcher viral four dollar toast pour-over, leggings Tumblr sustainable. 90's sartorial next level, kitsch messenger bag Williamsburg leggings McSweeney's four loko skateboard bespoke put a bird on it taxidermy bicycle rights. XOXO High Life master cleanse pork belly. Vice lumbersexual cornhole vinyl occupy. Kale chips photo booth ugh bespoke craft beer, Carles blog.
      </p>
    </div>
  </div>
</div>

app/views/remote_labs/_form.html.erb
<%= simple_form_for(@remote_lab) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :version %>
    <%= f.input :author %>
    <%= f.input :school %>
    <%= f.input :user_id %>
    <%= f.input :lab_type %>
    <%= f.input :allowable_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/remote_labs/edit.html.erb
<h1>Editing remote_lab</h1>

<%= render 'form' %>

<%= link_to 'Show', @remote_lab %> |
<%= link_to 'Back', remote_labs_path %>

app/views/remote_labs/index.html.erb
<h1>Listing remote_labs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Version</th>
      <th>Author</th>
      <th>School</th>
      <th>User</th>
      <th>Lab type</th>
      <th>Password</th>
      <th>Allowable time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @remote_labs.each do |remote_lab| %>
      <tr>
        <td><%= remote_lab.title %></td>
        <td><%= remote_lab.version %></td>
        <td><%= remote_lab.author %></td>
        <td><%= remote_lab.school %></td>
        <td><%= remote_lab.user_id %></td>
        <td><%= remote_lab.lab_type %></td>
        <td><%= remote_lab.password %></td>
        <td><%= remote_lab.allowable_time %></td>
        <td><%= link_to 'Show', remote_lab %></td>
        <td><%= link_to 'Edit', edit_remote_lab_path(remote_lab) %></td>
        <td><%= link_to 'Destroy', remote_lab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Remote lab', new_remote_lab_path %>

app/views/remote_labs/new.html.erb
<h1>New remote_lab</h1>

<%= render 'form' %>

<%= link_to 'Back', remote_labs_path %>

app/views/remote_labs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @remote_lab.title %>
</p>

<p>
  <strong>Version:</strong>
  <%= @remote_lab.version %>
</p>

<p>
  <strong>Author:</strong>
  <%= @remote_lab.author %>
</p>

<p>
  <strong>School:</strong>
  <%= @remote_lab.school %>
</p>

<p>
  <strong>User:</strong>
  <%= @remote_lab.user_id %>
</p>

<p>
  <strong>Lab type:</strong>
  <%= @remote_lab.lab_type %>
</p>

<p>
  <strong>Password:</strong>
  <%= @remote_lab.password %>
</p>

<p>
  <strong>Allowable time:</strong>
  <%= @remote_lab.allowable_time %>
</p>


<table class="table">
  <thead>
    <th>Address</th>
    <th>Type</th>
    <th>State</th>
    <th>Action</th>
  </thead>
  <tbody>
  <% @remote_lab.slaves.each do |slave| %>
    <tr>
      <td><%=slave.address%></td>
      <td><%=slave.s_type%></td>
      <td><%=slave.state%></td>
      <% if slave.s_type == 0 %>
        <td>
          <a class="switch-toggle btn btn-default btn-xs" data-id="<%=slave.id%>">
            Toggle
          </a>
        </td>
      <% elsif slave.s_type == 3 %>
        <td>
          <div id="<%= "#{slave.id}-graph" %>" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
          <script>
            $(function () {
              // Graph JS START
              var chartUrl = '/api/data_values?id=<%= slave.id %>';
              Highcharts.setOptions({
                global: {
                  useUTC: false
                }
              })
              var options = {
                title: {
                  text: 'TMP36 Slave'
                },
                chart: {
                  renderTo: '<%= slave.id %>-graph',
                  type: 'line'
                },
                xAxis: {
                  type: 'datetime',
                  title: {
                    text: 'Time'
                  }
                },
                plotOptions: {
                  line: {
                    animation: false
                  }
                },
                yAxis: {
                  title: {
                    text: 'Degrees C'
                  }
                },
                legend: {
                  enabled: false
                },
                credits: {
                  enabled: false
                },
                series: [{}]
              };
              $.getJSON(chartUrl, function (data) {
                var dataList = [];
                data.forEach(function (entry) {
                  heartrateInstance = [new Date(entry.created_at + "UTC").getTime(), parseFloat(entry.value)/100];
                  dataList.push(heartrateInstance);
                })
                options.series[0].data = dataList;
//                options.series[0].color = "#e51414";
                var chart = new Highcharts.Chart(options);
              });

              setInterval(function () {
                var dataList = [];
                $.getJSON(chartUrl, function (data) {
                  if (data.length == 0)
                    return;
                  if (new Date(data[data.length - 1].created_at).getTime() != options.series[0].data[options.series[0].data.length - 1][0]) {
                    data.forEach(function (entry) {
                      heartrateInstance = [new Date(entry.created_at).getTime(), parseFloat(entry.value)/100];
                      dataList.push(heartrateInstance);
                    })
                    options.series[0].data = dataList;
                    var chart = new Highcharts.Chart(options);
                  }
                })
              }, 5000);
            });
          </script>
        </td>
      <%end%>
    </tr>
  <% end %>

  </tbody>
</table>

<script>

  $('.switch-toggle').on('click', function(e) {
    var id = $(this).data('id');
    var url = "/slave/switch/toggle";

    $.ajax({
      type: "POST",
      url: url,
      data: {id: id}
    })
  })

</script>


<%= link_to 'Edit', edit_remote_lab_path(@remote_lab) %> |
<%= link_to 'Back', remote_labs_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td data-order="<%= user.last_sign_in_at.to_i %>">
  <%= user.last_sign_in_at.localtime.strftime("%B %d, %Y %H:%M") %>
</td>
<td data-order="<%= user.role %>">
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}, {}, {:disabled => user==current_user}) %>
  <% end %>
</td>
<td>
  <% unless user == current_user %>
    <%= link_to(user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-xs btn-danger') do %>
      <%= fa_icon "trash" %> Delete
    <% end %>
  <% end %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h3>User Management</h3>
      <hr>
      <table class="table table-striped" id="users-table">
        <thead>
          <th>Email Address</th>
          <th>Last Sign in</th>
          <th>Role</th>
          <th></th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
  // Initialise the user table
  $('#users-table').dataTable({
    "aoColumnDefs": [
      { 'bSortable': false, 'aTargets': [ 3 ] }
    ],
    "aLengthMenu": [[25, 50, 100, 200, -1], [25, 50, 100, 200, "All"]],
    "iDisplayLength": 25
  });

  // User Role Change AJAX submit
  $('#user_role').on('change', function(e) {
    var $form = $(this).parent('form');
    $.post($form.attr('action'), $form.serialize());
  })
</script>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <p>
        Mixtape crucifix kitsch hella blog PBR&B. Skateboard banh mi butcher normcore pug, 3 wolf moon seitan art party artisan narwhal swag organic Banksy DIY. Organic pork belly wayfarers fingerstache Shoreditch, deep v stumptown readymade. Crucifix Carles keytar stumptown pork belly, Tumblr single-origin coffee tofu art party Banksy Thundercats XOXO. Cred High Life VHS iPhone, pickled ethical banh mi Pinterest blog. Before they sold out asymmetrical Banksy, authentic retro cred paleo Schlitz. Cred sartorial PBR, fingerstache mumblecore 3 wolf moon gentrify vegan locavore.
      </p>
    </div>
  </div>
</div>